name: My First GitHub Action
# push, pull_request, deployment_status
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      # run is a bash command
      - uses: actions/checkout@v2
      - run: tree
